language: go

services:
  - mongodb

go:
  - 1.4
  - 1.5	 
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls

install:
  - go get -t -v ./...
  - mkdir -p $GOPATH/src/gopkg.in/tyba
  - cp -rf $PWD $GOPATH/src/gopkg.in/tyba/storable.v1

script:
  - go generate ./...
  - go test -v gopkg.in/tyba/storable.v1/generator
  - go test -v gopkg.in/tyba/storable.v1 -covermode=count -coverprofile=coverage.out
  - go test -v gopkg.in/tyba/storable.v1/operators -covermode=count -coverprofile=tmp.out
  - tail -n +2 tmp.out >> coverage.out
  - go test -v gopkg.in/tyba/storable.v1/tests -covermode=count -coverprofile=tmp.out
  - tail -n +2 tmp.out >> coverage.out

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken ttHfPtGawLnRyuGi8dxsddBDs1COrrI2o
